name: "Download fake relay"
description: "Download fake relay for integration tests"
runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Clone remote repository
      shell: bash
      run: |
        git clone https://github.com/flashbots/suave-playground.git

    - name: Build and run
      shell: bash
      run: |
        cd suave-playground
        go build -v -o suave-playground .
        echo "$PWD" >> $GITHUB_PATH

    - name: Install reth & lighthouse
      shell: bash
      run: |
        ./suave-playground download-artifacts
        echo "$PWD" >> $GITHUB_PATH/output
