[workspace]
members = [
    "crates/rbuilder",
    "crates/rbuilder/src/test_utils"
]
resolver = "2"

# Like release, but with full debug symbols. Useful for e.g. `perf`.
[profile.debug-fast]
inherits = "release"
debug = true

[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1
incremental = false

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
reth = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.1" }
reth-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.1" }
reth-db-common = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.1" }
reth-errors = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.1" }
reth-libmdbx = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.1" }
reth-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.1" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.1" }
reth-trie = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.1" }
reth-trie-parallel = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.1" }
reth-basic-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.1" }
reth-node-core = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.1" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.1" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.1", features = ["test-utils"] }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.1" }
reth-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.1" }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.0.1" }

# version is copied from reth  "v1.0.1" dependencies
revm = { version = "11.0.0", features = [
    "std",
    "secp256k1",
    "optional_balance_check",
], default-features = false }
revm-primitives = { version = "6.0.0", features = [
    "std",
], default-features = false }
revm-inspectors = { git = "https://github.com/paradigmxyz/evm-inspectors", rev = "dc614ee" }

ethereum_ssz_derive = "0.5"
ethereum_ssz = "0.5"

alloy-primitives = "0.7.2"
alloy-rlp = "0.3.4"
alloy-chains = { version = "0.1.15", feature = ["serde", "rlp", "arbitrary"] }
alloy-provider = { git = "https://github.com/alloy-rs/alloy", version = "0.2" }
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", version = "0.2" }
alloy-json-rpc = { git = "https://github.com/alloy-rs/alloy", version = "0.2" }
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", version = "0.2" }
alloy-network = { git = "https://github.com/alloy-rs/alloy", version = "0.2" }
alloy-transport = { git = "https://github.com/alloy-rs/alloy", version = "0.2" }
alloy-node-bindings = { git = "https://github.com/alloy-rs/alloy", version = "0.2" }
alloy-consensus = { git = "https://github.com/alloy-rs/alloy", version = "0.2", features = ["kzg"] }
alloy-serde = { git = "https://github.com/alloy-rs/alloy", version = "0.2" }
alloy-rpc-types-beacon = { git = "https://github.com/alloy-rs/alloy", version = "0.2", features = [
    "ssz",
] }
alloy-rpc-types-engine = { git = "https://github.com/alloy-rs/alloy", version = "0.2", features = [
    "ssz",
] }
alloy-rpc-types-eth = { git = "https://github.com/alloy-rs/alloy", version = "0.2" }
alloy-signer-local = { git = "https://github.com/alloy-rs/alloy", version = "0.2" }
